### ISSUE TITLE
about the size of origin and output

### ISSUE THREAD

**Issue by tuqiangwang** [nian-liu/PiCANet#4]
Hello, the size of your network output is 224x224, why ca n’t it be the same as the original image?

**Comment by nian-liu** [comment]
Cuz the global attention model requires a fixed spatial size for the feature map.

**Comment by tuqiangwang** [comment]
Can the final output image be the same size as the input image?

**Comment by nian-liu** [comment]
@tuqiangwang The model can only output an effective saliency map with size 224*224. The test code with the Matlab wrapper resizes the outputted saliency map back to the original size of the input image with bilinear interpolation.
